import 'package:dart_style/dart_style.dart';

import '../models/datasource_info.dart';

/// Generates integration test files for GET datasource endpoints.
///
/// Each generated test file contains a single test group for the endpoint,
/// with a setUp that creates a fresh Dio client and datasource instance, and
/// a single test that calls the datasource method directly with exception
/// handling for Dio errors.
class IntegrationTestGenerator {
  final _fmt =
      DartFormatter(languageVersion: DartFormatter.latestLanguageVersion);

  /// Generates a complete integration test file for the given endpoint.
  ///
  /// The returned Dart source code imports the datasource class, creates
  /// a test group, sets up a Dio client and datasource instance, and calls
  /// the datasource method with exception handling for Dio errors.
  ///
  /// Requires [packageName] to construct the import path to the datasource.
  String generate(EndpointInfo endpoint, {required String packageName}) {
    final importPath = _calculateImportPath(
      sourceFilePath: endpoint.sourceFilePath,
      packageName: packageName,
    );

    final buffer = StringBuffer();
    buffer.writeln('// GENERATED BY mogen_integration_tests — DO NOT EDIT');
    buffer.writeln('// ignore_for_file: lines_longer_than_80_chars');
    buffer.writeln();
    buffer.writeln("import 'package:dio/dio.dart';");
    buffer.writeln("import '../../dio_helper.dart';");
    buffer.writeln("import '$importPath';");
    buffer.writeln();
    buffer.writeln('void main() {');
    buffer.writeln("  group('GET ${endpoint.endpoint}', () {");
    buffer.writeln('    late Dio dio;');
    buffer.writeln('    late ${endpoint.className} datasource;');
    buffer.writeln();
    buffer.writeln('    setUp(() {');
    buffer.writeln('      dio = buildTestDio();');
    buffer.writeln('      datasource = ${endpoint.className}(dio);');
    buffer.writeln('    });');
    buffer.writeln();
    final args = endpoint.callArguments.isNotEmpty
        ? '(${endpoint.callArguments})'
        : '()';
    buffer.writeln(
        "    test('calls ${endpoint.methodName}() successfully', () async {");
    buffer.writeln('      try {');
    buffer.writeln('        await datasource.${endpoint.methodName}$args;');
    buffer.writeln('      } on DioException catch (e) {');
    buffer.writeln(
        '        // A DioException means the request reached the server.');
    buffer.writeln(
        '        // Fail only on connectivity errors, not HTTP error codes.');
    buffer.writeln('        if (e.type == DioExceptionType.connectionError ||');
    buffer.writeln('            e.type == DioExceptionType.unknown) {');
    buffer.writeln('          fail(\'Connection failed: \${e.message}\');');
    buffer.writeln('        }');
    buffer.writeln('      }');
    buffer.writeln('    });');
    buffer.writeln('  });');
    buffer.writeln('}');

    try {
      return _fmt.format(buffer.toString());
    } catch (_) {
      return buffer.toString();
    }
  }

  /// Calculates the package-relative import path from the datasource file path.
  String _calculateImportPath({
    required String sourceFilePath,
    required String packageName,
  }) {
    final normalized = sourceFilePath.replaceAll('\\', '/');
    final libIndex = normalized.indexOf('/lib/');
    if (libIndex >= 0) {
      final relativePath = normalized.substring(libIndex + 5);
      return 'package:$packageName/$relativePath';
    }
    return 'package:$packageName/lib/features/unknown.dart';
  }
}
